<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notes préliminaires</title>
</head>
<body>
    <p>
    Notes préliminaires
Vous trouverez ci-dessous un ensemble d’énoncés pour lesquels il vous faudra fournir au moins un programme PHP.
Il existe pour chaque énoncé plusieurs solutions envisageables : à vous de développer votre réflexion afin de proposer quelques-unes des ces solutions (certaines seront plus ou moins claires, d’autres plus ou moins efficaces).
    </p>
</body>
</html>